outsourcing/src/main/java/entities/Cliente.java
/**
 * 
 */
package entities;

import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@ViewScoped
@ManagedBean
@Entity
@Table(name = "Cliente")
public class Cliente {
	@Id
	@Column
	private int Nit;
	@Column
	private String NombreCliente;
	@Column
	private Date FechaContacto;
	@Column
	private int CodDirector;
	@Column
	private int CodigoVertical;
	@Column
	private int CodigoUsuarioDirector;
	
	public int getCodigoUsuarioDirector() {
		return CodigoUsuarioDirector;
	}
	public void setCodigoUsuarioDirector(int codigoUsuarioDirector) {
		CodigoUsuarioDirector = codigoUsuarioDirector;
	}
	public int getNit() {
		return Nit;
	}
	public void setNit(int nit) {
		Nit = nit;
	}
	public String getNombreCliente() {
		return NombreCliente;
	}
	public void setNombreCliente(String nombreCliente) {
		NombreCliente = nombreCliente;
	}
	public Date getFechaContacto() {
		return FechaContacto;
	}
	public void setFechaContacto(Date fechaContacto) {
		FechaContacto = fechaContacto;
	}
	public int getCodDirector() {
		return CodDirector;
	}
	public void setCodDirector(int codDirector) {
		CodDirector = codDirector;
	}
	public int getCodigoVertical() {
		return CodigoVertical;
	}
	public void setCodigoVertical(int codVertical) {
		CodigoVertical = codVertical;
	}
	
}

outsourcing/src/main/java/Clientes/ClienteController.java
package Clientes;
import java.util.List;

import javax.faces.bean.ManagedBean;

import boundary.ClienteBoundary;
import boundary.RequerimientosBoundary;
import entities.Cliente;

@ManagedBean
public class ClienteController {
	private List<Cliente> clientes;

	public List<Cliente> getClientes() {
		ClienteBoundary clienteBoundary = new ClienteBoundary();
		clientes = clienteBoundary.obtenerClientes();
		return clientes;
	}

	public void setClientes(List<Cliente> clientes) {
		this.clientes = clientes;
	}

	

	

}

outsourcing/src/main/webapp/Clientes/Cliente.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Cliente</title>
	<h:outputStylesheet library="css" name="styles.css" />
</h:head>

<body>
	<p:panel class="header">
		<h:graphicImage library="img" name="logo.png" class="logo" />
		<p:commandButton value="Salir" class="boton salir"
			icon="ui-icon-extlink" />
	</p:panel>
	<div class="contenedor">
		<p:panel class="banner">
			<h:form>
				<p:growl id="messages" showDetail="false" />
				<p:panelMenu style="width:180px">
					<p:submenu label="Diligenciar">
						<p:menuitem value="Captura" icon="ui-icon-clock"
							url="../Capturas/Captura.jsf" />
					</p:submenu>
					<p:submenu label="Gestion">
						<p:menuitem value="Usuarios" ajax="false" icon="ui-icon-person"
							url="../Usuarios/Usuarios.jsf" />
						<p:menuitem value="Vertical" ajax="false"
							icon="ui-icon-arrowthick-2-n-s"
							url="../Verticales/Verticales.jsf" />
						<p:menuitem value="Proyectos" ajax="false" icon="ui-icon-suitcase"
							url="../Proyectos/Proyectos.jsf" />
						<p:menuitem value="Requerimientos" ajax="false"
							icon="ui-icon-circle-check"
							url="../Requerimientos/Requerimientos.jsf" />
						<p:menuitem value="Cliente" ajax="false" icon="ui-icon-contact" />
						<p:menuitem value="Rol" ajax="false" icon="ui-icon-tag"
							url="../Rol/Rol.jsf" />
					</p:submenu>
					<p:separator />
					<p:submenu label="Consulta">
						<p:submenu label="Matriz" icon="ui-icon-script">

							<p:menuitem value="General" url="../Matriz/MatrizGeneral.jsf"
								icon="ui-icon-zoomout" />
							<p:menuitem value="Detalle" url="../Matriz/MatrizDetalle.jsf"
								icon="ui-icon-zoomin" />

						</p:submenu>
					</p:submenu>
				</p:panelMenu>
			</h:form>
			<p:panel class="panel" header="Cliente" style="margin-bottom:20px">
				<!-- Contenido dentro del panel  -->
				<p:commandButton value="Nuevo" class="boton" id="Nuevo"
					icon="ui-icon-plus" onclick="PF('dlg3').show();" />
				<p:commandButton value="Editar" class="boton" id="Editar"
					icon="ui-icon-pencil" onclick="PF('dlg2').show();" />
				<p:commandButton value="Borrar" class="boton" id="Borrar"
					icon="ui-icon-closethick" onclick="PF('dlg1').show();" />
				<p:inputText style="margin-right:10px" class="buscar"
					placeholder="Buscar.." />
				<!-- Elementos Modal -->
				<!-- Formulario Nuevo -->
				<p:dialog header="Nuevo" widgetVar="dlg3" modal="true">
					<h:form class="formCliente">
					<p:inputText placeholder="Nit" />&nbsp;
					<p:inputText placeholder="Nombre" />
					<br />
					<br />
					<p:calendar value="#{calendarView.date9}" pattern="dd-MM-yyyy"
						mask="true" placeholder="Fecha de contacto" />
					<br />
					<p:outputLabel for="vertical" value="Vertical:" />
					<div class="emptyBox"></div>
					<p:selectOneMenu id="vertical" value="" effect="fold"
						editable="true">
						<f:selectItem itemLabel="financiera" />
					</p:selectOneMenu>
					<br />
					<br />
					<p:outputLabel for="director" value="Director:" />
					<div class="emptyBox"></div>
					<p:selectOneMenu id="director" value="" effect="fold"
						editable="true">
						<f:selectItem itemLabel="pepito" />
					</p:selectOneMenu>
					<br />
					<br />
					<p:commandButton value="Guardar" class="boton Guardar"
						icon="ui-icon-disk" />
					<p:commandButton value="Borrar" class="boton Borrar"
						icon="ui-icon-alert" />
					<p:commandButton value="Cancelar" class="boton Cancelar1"
						icon="ui-icon-closethick" />
						</h:form>
				</p:dialog>
				<!-- Formulario editar -->
				<p:dialog header="Editar" widgetVar="dlg2" modal="true">
					<h:form class="formCliente">
					<p:inputText placeholder="Nit" />&nbsp;
					<p:inputText placeholder="Nombre" />
					<br />
					<br />
					<p:calendar value="#{calendarView.date9}" pattern="dd-MM-yyyy"
						mask="true" placeholder="Fecha de contacto" />
					<br />
					<p:outputLabel for="vertical2" value="Vertical:" />
					<div class="emptyBox"></div>
					<p:selectOneMenu id="vertical2" value="" effect="fold"
						editable="true">
						<f:selectItem itemLabel="financiera" />
					</p:selectOneMenu>
					<br />
					<br />
					<p:outputLabel for="director2" value="Director:" />
					<div class="emptyBox"></div>
					<p:selectOneMenu id="director2" value="" effect="fold"
						editable="true">
						<f:selectItem itemLabel="pepito" />
					</p:selectOneMenu>
					<br />
					<br />
					<p:commandButton value="Actualizar" class="boton Actualizar"
						icon="ui-icon-disk" />
					<p:commandButton value="Cancelar" class="boton CancelarEditar"
						icon="ui-icon-closethick" />
						</h:form>
				</p:dialog>
				<!-- Ventana borrar-->
				<p:dialog header="Atencion!" widgetVar="dlg1" modal="true"
					height="100">
					<h:outputText
						value="Estas apunto de borrar un cliente, estas seguro?" />
					<br />
					<br />
					<p:commandButton value="Si, borrar" class="boton" id="siBorrar"
						icon="ui-icon-trash" />
					<p:commandButton value="Cancelar" class="boton" id="Cancelar3"
						icon="ui-icon-closethick" />
				</p:dialog>
				<br />
				<p:dataTable var="cliente" class="tabla" value="#{clienteController.clientes}" rows="10"
				paginator="true"
				paginatorTemplate="{CurrentPageReport} {FirstPageLink}
				{PreviousPageLink} {PageLinks}
				{NextPageLink} {LastPageLink}
				{RowsPerPageDropdown}"
				rowsPerPageTemplate="5,10,15">
					<p:column headerText="Codigo">
						<h:outputText value="#{cliente.nit}"/>
					</p:column>
					<p:column headerText="Nombre">
						<h:outputText value="#{cliente.nombreCliente}"/>
					</p:column>
					<p:column headerText="Fecha Contacto">
						<h:outputText value="#{cliente.fechaContacto}"/>
					</p:column>
					<p:column headerText="Codigo Director">
						<h:outputText value="#{cliente.codDirector}"/>
					</p:column>
					<p:column headerText="Codigo Vertical">
						<h:outputText value="#{cliente.codigoVertical}"/>
					</p:column>
					<p:column headerText="Codigo Usuario Director">
						<h:outputText value="#{cliente.codigoUsuarioDirector}"/>
					</p:column>
				</p:dataTable>
			</p:panel>
		</p:panel>
	</div>
</body>

</html>