outsourcing/src/main/java/entities/Proyecto.java
package entities;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@ViewScoped
@ManagedBean
@Entity
@Table(name = "Proyecto")
public class Proyecto {
	@Id
	private int CodigoProyecto;
	private String NombreProyecto;
	private int NitCliente;

	public int getCodigoProyecto() {
		return CodigoProyecto;
	}

	public void setCodigoProyecto(int codigoProyecto) {
		CodigoProyecto = codigoProyecto;
	}

	public String getNombreProyecto() {
		return NombreProyecto;
	}

	public void setNombreProyecto(String nombreProyecto) {
		NombreProyecto = nombreProyecto;
	}

	public int getNitCliente() {
		return NitCliente;
	}

	public void setNitCliente(int NitCliente) {
		this.NitCliente = NitCliente;
	}

}

outsourcing/src/main/java/Proyectos/ProyectoController.java
package Proyectos;
import java.util.List;

import javax.faces.bean.ManagedBean;

import boundary.ProyectosBoundary;
import entities.Proyecto;

@ManagedBean
public class ProyectoController {
	private List<Proyecto> proyectos;

	public List<Proyecto> getProyectos() {
		ProyectosBoundary proyectosBoundary = new ProyectosBoundary();
		proyectos = proyectosBoundary.obtenerProyectos();
		return proyectos;
	}

	public void setProyectos(List<Proyecto> proyectos) {
		this.proyectos = proyectos;
	}	

}

outsourcing/src/main/webapp/Proyectos/Proyectos.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Proyectos</title>
	<h:outputStylesheet library="css" name="styles.css" />
</h:head>

<body>
	<p:panel class="header">
		<h:graphicImage library="img" name="logo.png" class="logo" />
		<p:commandButton value="Salir" class="boton salir"
			icon="ui-icon-extlink" />
	</p:panel>
	<div class="contenedor">
		<p:panel class="banner">
			<h:form>
				<p:growl id="messages" showDetail="false" />
				<p:panelMenu style="width:180px">
					<p:submenu label="Diligenciar">
						<p:menuitem value="Captura" icon="ui-icon-clock"
							url="../Capturas/Captura.jsf" />
					</p:submenu>
					<p:submenu label="Gestion">
						<p:menuitem value="Usuarios" ajax="false" icon="ui-icon-person"
							url="../Usuarios/Usuarios.jsf" />
						<p:menuitem value="Vertical" ajax="false"
							icon="ui-icon-arrowthick-2-n-s"
							url="../Verticales/Verticales.jsf" />
						<p:menuitem value="Proyectos" ajax="false" icon="ui-icon-suitcase" />
						<p:menuitem value="Requerimientos" ajax="false"
							icon="ui-icon-circle-check"
							url="../Requerimientos/Requerimientos.jsf" />
						<p:menuitem value="Cliente" ajax="false" icon="ui-icon-contact"
							url="../Clientes/Cliente.jsf" />
							<p:menuitem value="Rol" ajax="false" icon="ui-icon-tag"
							url="../Rol/Rol.jsf" />
					</p:submenu>
					<p:separator />
					<p:submenu label="Consulta">
						<p:submenu label="Matriz" icon="ui-icon-script">

							<p:menuitem value="General" url="../Matriz/MatrizGeneral.jsf"
								icon="ui-icon-zoomout" />
							<p:menuitem value="Detalle" url="../Matriz/MatrizDetalle.jsf"
								icon="ui-icon-zoomin" />

						</p:submenu>
					</p:submenu>
				</p:panelMenu>
			</h:form>
			<p:panel class="panel" header="Proyectos" style="margin-bottom:20px">
				<!-- Contenido dentro del panel  -->
				<p:commandButton value="Nuevo" class="boton" id="Nuevo"
					icon="ui-icon-plus" onclick="PF('dlg3').show();" />
				<p:commandButton value="Editar" class="boton" id="Editar"
					icon="ui-icon-pencil" onclick="PF('dlg2').show();" />
				<p:commandButton value="Borrar" class="boton" id="Borrar"
					icon="ui-icon-closethick" onclick="PF('dlg1').show();" />
				<p:inputText style="margin-right:10px" class="buscar"
					placeholder="Buscar.." />
				<!-- Elementos Modal -->
				<!-- Formulario Nuevo -->
				<p:dialog header="Nuevo" widgetVar="dlg3" modal="true">
				<h:form class="formProyectos">
					<p:inputText placeholder="Nombre del proyecto" /><br />
					<p:outputLabel for="cliente" value="Cliente:    " />
					<div class="emptyBox"></div>
					<p:selectOneMenu id="cliente" value="" effect="fold"
						editable="true">
						<f:selectItem itemLabel="Bancolombia" itemValue="" />
						<f:selectItems value="" />
					</p:selectOneMenu>
					<br />
					<br />
					<p:commandButton value="Guardar" class="boton Guardar"
						icon="ui-icon-disk" />
					<p:commandButton value="Borrar" class="boton Borrar1"
						icon="ui-icon-alert" />
					<p:commandButton value="Cancelar" class="boton Cancelar1"
						icon="ui-icon-closethick" />
						</h:form>
				</p:dialog>
				<!-- Formulario editar -->
				<p:dialog header="Editar" widgetVar="dlg2" modal="true">
				<h:form class="formProyectos">
					<p:inputText placeholder="Nombre del proyecto" /><br />
					<p:outputLabel for="cliente2" value="Cliente:    " />
					<div class="emptyBox"></div>
					<p:selectOneMenu id="cliente2" value="" effect="fold"
						editable="true">
						<f:selectItem itemLabel="Bancolombia" itemValue="" />
						<f:selectItems value="" />
					</p:selectOneMenu>
					<br />
					<br />
					<p:commandButton value="Actualizar" class="boton Actualizar1"
						icon="ui-icon-disk" />
					<p:commandButton value="Cancelar" class="boton CancelarEditar1"
						icon="ui-icon-closethick" />
						</h:form>
				</p:dialog>
				<!-- Ventana borrar-->
				<p:dialog header="Atencion!" widgetVar="dlg1" modal="true"
					height="100">
					<h:outputText
						value="Estas apunto de borrar un proyecto, estas seguro?" />
					<br />
					<br />
					<p:commandButton value="Si, borrar" class="boton" id="siBorrar"
						icon="ui-icon-trash" />
					<p:commandButton value="Cancelar" class="boton" id="Cancelar3"
						icon="ui-icon-closethick" />
				</p:dialog>
				<br />
				<p:dataTable var="proyecto" class="tabla" value="#{proyectoController.proyectos}" rows="10"
				paginator="true"
				paginatorTemplate="{CurrentPageReport} {FirstPageLink}
				{PreviousPageLink} {PageLinks}
				{NextPageLink} {LastPageLink}
				{RowsPerPageDropdown}"
				rowsPerPageTemplate="5,10,15">
					<p:column headerText="Codigo">
						<h:outputText value="#{proyecto.codigoProyecto}"/>
					</p:column>
					<p:column headerText="Nombre">
						<h:outputText value="#{proyecto.nombreProyecto}"/>
					</p:column>
					<p:column headerText="Codigo Cliente">
						<h:outputText value="#{proyecto.nitCliente}"/>
					</p:column>
				</p:dataTable>
			</p:panel>
		</p:panel>
	</div>
</body>

</html>